from typing import List, Protocol

class ClientBase(Protocol):
    async def get_credits_by_track_id(self, track_id: str): ...
    async def get_credits_by_track_ids(self, track_ids: List[str]): ...
    async def get_playlist_tracks(self, playlist_id: str): ...
